memory_limit=512M
max_execution_time=60
post_max_size=512M
upload_max_filesize=512M
max_input_vars=5000

log_errors=On
error_log=/proc/self/fd/2

zend.exception_ignore_args=1

date.timezone=UTC

[opcache]
opcache.enable=1
opcache.validate_timestamps=1
opcache.revalidate_freq=0
opcache.max_accelerated_files=10000
opcache.memory_consumption=192
opcache.interned_strings_buffer=16
